services:
  backend:
    image: chekoledocker/adwa-aiassistant-backend:latest
    build:
      context: ./backend

    ports:
      - "10000:10000"

    env_file:
      - ./backend/.env

    environment:
      - PORT=10000

    volumes:
      - ./backend/adwa_db_v2:/app/adwa_db_v2
      - ./backend/data:/app/data:ro

    restart: unless-stopped